In [8]:
# Install a pip package in the current Jupyter kernel
import sys
!{sys.executable} -m pip install numpy
!{sys.executable} -m pip install pandas
!{sys.executable} -m pip install -U scikit-learn

Requirement already up-to-date: scikit-learn in /home/dev/.local/lib/python3.8/site-packages (0.24.1)


Scikit comes with a few pre loaded data sets. The one we are going to use is a dataset for house prices called Boston.

In [40]:
from sklearn import datasets
boston = datasets.load_boston()
print(boston.data) # The X
print(boston.target) # The Y
print(boston.feature_names) # The name of the columns of X

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]
[24.  21.6 34.7 33.4 36.2 28.7 22.9 27.1 16.5 18.9 15.  18.9 21.7 20.4
 18.2 19.9 23.1 17.5 20.2 18.2 13.6 19.6 15.2 14.5 15.6 13.9 16.6 14.8
 18.4 21.  12.7 14.5 13.2 13.1 13.5 18.9 20.  21.  24.7 30.8 34.9 26.6
 25.3 24.7 21.2 19.3 20.  16.6 14.4 19.4 19.7 20.5 25.  23.4 18.9 35.4
 24.7 31.6 23.3 19.6 18.7 16.  22.2 25.  33.  23.5 19.4 22.  17.4 20.9
 24.2 21.7 22.8 23.4 24.1 21.4 20.  20.8 21.2 20.3 28.  23.9 24.8 22.9
 23.9 26.6 22.5 22.2 23.6 28.7 22.6 22.  22.9 25.  20.6 28.4 21.4 38.7
 43.8 33.2 27.5 26.5 18.6 19.3 20.1 19.5 19.5 20.4 19.8 19.

#### There are two problems with any datasets which are quite evident
* There are missing values
* Some values are in the order of 10^(-3) and others which are 10^(2). The values in the order 10^(2) will affect the model more (in multi variable regression). But is it always desirable?

In [10]:
import pandas as pd

In [14]:
# Converting the dataset into a pandas data frame

# the first argument is the 2d array and the 2nd argument is the name of the columns
X_df = pd.DataFrame(boston.data,columns=boston.feature_names) 

# making a data frame for the Y variable which is to be predicted
Y_df = pd.DataFrame(boston.target)

In [15]:
X_df.head(5) # just gives us the first 5 values of the data frame

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

Before this we made a model but we had nothing to test it with and see if it was accurate.  
So let us spilt the data set into two using sklearn.

In [20]:
from sklearn.model_selection import train_test_split

In [22]:
# This splits the data into 20 percent testing and 80 percent training data (ever heard of the 80-20 rule?)

X_train,X_test,Y_train,Y_test = train_test_split(X_df, Y_df, test_size=0.2, random_state=3)
# Not related to data science but can computers genrate random numbers?

In [23]:
X_train.head()

CRIM    ZN  INDUS  CHAS     NOX     RM   AGE     DIS   RAD    TAX  \
454   9.51363   0.0  18.10   0.0  0.7130  6.728  94.1  2.4961  24.0  666.0   
471   4.03841   0.0  18.10   0.0  0.5320  6.229  90.7  3.0993  24.0  666.0   
281   0.03705  20.0   3.33   0.0  0.4429  6.968  37.2  5.2447   5.0  216.0   
477  15.02340   0.0  18.10   0.0  0.6140  5.304  97.3  2.1007  24.0  666.0   
107   0.13117   0.0   8.56   0.0  0.5200  6.127  85.2  2.1224   5.0  384.0   

     PTRATIO       B  LSTAT  
454     20.2    6.68  18.71  
471     20.2  395.33  12.87  
281     14.9  392.23   4.59  
477     20.2  349.48  24.91  
107     20.9  387.69  14.09

# Regression
Now we are going to do linear regression but with multiple variables.  
The algorithm is the same as the one with one variable except the cost function is slightly modified.  
Watch [4.1-4.2](https://www.youtube.com/watch?v=Q4GNLhRtZNc&list=PLLssT5z_DsK-h9vYZkQkYNWcItqhlRJLN&index=18)

In [25]:
from sklearn import linear_model
from sklearn.metrics import mean_squared_error

In [26]:
# defining a linear regression model

reg = linear_model.LinearRegression()

In [29]:
reg.fit(X_train,Y_train) # to train the model

LinearRegression()

In [30]:
# the value of the theta, i.e. the weights
reg.coef_

array([[-1.23897571e-01,  4.81822924e-02, -4.74497796e-02,
         3.36938950e+00, -1.56635488e+01,  3.59419367e+00,
        -9.33206067e-03, -1.47089101e+00,  3.05053544e-01,
        -1.08397039e-02, -9.08791339e-01,  1.00352939e-02,
        -4.77714677e-01]])

In [33]:
# predicting the values of the test data

Y_pred = reg.predict(X_test)

In [34]:
error = mean_squared_error(Y_pred,Y_test)
error

16.943073013833807

# Pre Processing Data  
To solve the problem of null data refer to [this article](https://towardsdatascience.com/data-preprocessing-with-python-pandas-part-1-missing-data-45e76b781993)

# Normalization  
This is done to solve the 2nd problem.
There are three basic methods:
* Max scaling
* Min-Max scaling
* Standardization

## Max Scaling  
Just divide the values by the maximum absolute value present in that column.  
Range of data after this normalization [-1,1]

In [35]:
df_1 = X_df.copy()
  
# Max Scaling
for col in df_1.columns:
    df_1[col] = df_1[col]/ df_1[col].abs().max()
    
df_1.head()

CRIM    ZN     INDUS  CHAS       NOX        RM    AGE       DIS  \
0  0.000071  0.18  0.083273   0.0  0.617681  0.748861  0.652  0.337278   
1  0.000307  0.00  0.254867   0.0  0.538462  0.731321  0.789  0.409607   
2  0.000307  0.00  0.254867   0.0  0.538462  0.818337  0.611  0.409607   
3  0.000364  0.00  0.078587   0.0  0.525832  0.797039  0.458  0.499913   
4  0.000776  0.00  0.078587   0.0  0.525832  0.814009  0.542  0.499913   

        RAD       TAX   PTRATIO         B     LSTAT  
0  0.041667  0.416315  0.695455  1.000000  0.131156  
1  0.083333  0.340366  0.809091  1.000000  0.240716  
2  0.083333  0.340366  0.809091  0.989746  0.106136  
3  0.125000  0.312236  0.850000  0.994281  0.077430  
4  0.125000  0.312236  0.850000  1.000000  0.140374

## Min-Max Scaling  
Subtract the minimum value and divide by the range (max - min) of the values.  
Range of data after this normalization [0,1]

In [36]:
df_2 = X_df.copy()
  
# Min-Max Scaling
for col in df_2.columns:
    df_2[col] = (df_2[col] - df_2[col].min()) / (df_2[col].max() - df_2[col].min())   

df_2.head()

CRIM    ZN     INDUS  CHAS       NOX        RM       AGE       DIS  \
0  0.000000  0.18  0.067815   0.0  0.314815  0.577505  0.641607  0.269203   
1  0.000236  0.00  0.242302   0.0  0.172840  0.547998  0.782698  0.348962   
2  0.000236  0.00  0.242302   0.0  0.172840  0.694386  0.599382  0.348962   
3  0.000293  0.00  0.063050   0.0  0.150206  0.658555  0.441813  0.448545   
4  0.000705  0.00  0.063050   0.0  0.150206  0.687105  0.528321  0.448545   

        RAD       TAX   PTRATIO         B     LSTAT  
0  0.000000  0.208015  0.287234  1.000000  0.089680  
1  0.043478  0.104962  0.553191  1.000000  0.204470  
2  0.043478  0.104962  0.553191  0.989737  0.063466  
3  0.086957  0.066794  0.648936  0.994276  0.033389  
4  0.086957  0.066794  0.648936  1.000000  0.099338

## Standardization  
In this we subtract the mean from each value and then divide by the standard deviation.

In [42]:
df_3 = X_df.copy()
  
# Standardization
for col in df_3.columns:
    df_3[col] = (df_3[col] - df_3[col].mean())/ df_3[col].std()
    
df_3.head()

CRIM        ZN     INDUS      CHAS       NOX        RM       AGE  \
0 -0.419367  0.284548 -1.286636 -0.272329 -0.144075  0.413263 -0.119895   
1 -0.416927 -0.487240 -0.592794 -0.272329 -0.739530  0.194082  0.366803   
2 -0.416929 -0.487240 -0.592794 -0.272329 -0.739530  1.281446 -0.265549   
3 -0.416338 -0.487240 -1.305586 -0.272329 -0.834458  1.015298 -0.809088   
4 -0.412074 -0.487240 -1.305586 -0.272329 -0.834458  1.227362 -0.510674   

        DIS       RAD       TAX   PTRATIO         B     LSTAT  
0  0.140075 -0.981871 -0.665949 -1.457558  0.440616 -1.074499  
1  0.556609 -0.867024 -0.986353 -0.302794  0.440616 -0.491953  
2  0.556609 -0.867024 -0.986353 -0.302794  0.396035 -1.207532  
3  1.076671 -0.752178 -1.105022  0.112920  0.415751 -1.360171  
4  1.076671 -0.752178 -1.105022  0.112920  0.440616 -1.025487

Let us fit the data again but now after normalizing data.

In [41]:
reg_n = linear_model.LinearRegression(normalize=True)
reg_n.fit(X_train,Y_train) 
Y_pred_n = reg_n.predict(X_test)
error = mean_squared_error(Y_pred_n,Y_test)
error 

# There is almost no difference in the error, we need to find other ways to reduce the error

16.94307301383376